<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYYxQyY9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYYxQyY9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYYxQyY9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYYxQyY9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYYxQyY9\App_KernelDevDebugContainer([
    'container.build_hash' => 'YYxQyY9',
    'container.build_id' => '7002e6a2',
    'container.build_time' => 1680868320,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYYxQyY9');
