<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGZ3YE7t\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGZ3YE7t/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGZ3YE7t.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGZ3YE7t\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGZ3YE7t\App_KernelDevDebugContainer([
    'container.build_hash' => 'GZ3YE7t',
    'container.build_id' => '9afc3493',
    'container.build_time' => 1680628950,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGZ3YE7t');
